name = "xray"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true


account_id = "c94c08c1fa3eb249700c89571fc3a332"
workers_dev = true

[[kv_namespaces]]
binding = "YUMI"
id = "03c4102cd66446d3af2c1a2893243be7"

[build]
command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

[vars]
UUID = "2bcfbfba-b446-4ad5-93ad-72af9e008f61"
