name = "xray"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true


account_id = "58408afca3d99078ac3dea7125dc5824"
workers_dev = true

[[kv_namespaces]]
binding = "YUMI"
id = "a2823e711dd7453498ed483e3b7b82a8"

[build]
command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

[vars]
UUID = "2bcfbfba-b446-4ad5-93ad-72af9e008f61"
